Shit.delete_all
Shit.create(author: 'El ramo de transmedia', reason: 'es muy fome', featured: true )
Shit.create(author: 'Pedro', reason: 'siempre faltar a todo.', featured: true )
Shit.create(author: 'La UDI', reason: 'fachos y ladrones', featured: true )
Shit.create(author: 'La Sol', reason: 'no saber usar Illustrator', featured: true )
Shit.create(author: 'Los pájaros y toda su familia', reason: 'sólo saben volar', featured: true )
Shit.create(author: 'La gente en general', reason: 'valen callampa', featured: true )
Shit.create(author: 'Los terremotos', reason: 'Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue. Donec ullamcorper nulla non metus auctor fringilla. Sed posuere consectetur est at lobortis.', featured: true )
Shit.create(author: 'El fútbol', reason: 'es el verdadero opio del pueblo', featured: true )
Shit.create(author: 'La Universidad', reason: 'es demasiado larga!!!!', featured: true )
Shit.create(author: 'Los españoles', reason: 'flojos y mantenidos', featured: true )
Shit.create(author: 'El horóscopo', reason: 'hippies vagos de mierda', featured: true )
Shit.create(author: 'Mecánica estructural', reason: 'es un ramo de mierda', featured: true )
Shit.create(author: 'Yo mismo', reason: 'hay veces que me odio mucho', featured: true )
Shit.create(author: 'Mi compañera de pega', reason: 'me "ayudó" pero hizo todo mal y perdí toda la tarde en corregir sus errores', featured: true )
Shit.create(author: 'Taylor Swift', reason: 'propone un modelo femenino demasiado perfecto y a las mujeres nos da depresión no ser así', featured: true )
Shit.create(author: 'Una señora homofóbica', reason: 'me dijo que siendo gay no podía ser feliz y que me iría al infierno y moriría solo como un perro', featured: true )
Shit.create(author: 'Mi reportaje de edición Tv', reason: 'nicagando alcanzo a terminarlo y me tiene muy estresado', featured: true )
Shit.create(author: 'Los weones que te patean y te vuelven a hablar', reason: 'sientes que te tienen pal webeo', featured: true )
Shit.create(author: 'La gente peladora', reason: 'qué se creen para andar criticando a otros', featured: true )
Shit.create(author: 'Las selfies poseras', reason: 'ni que fueran Kim Kardashian', featured: true )
Shit.create(author: 'La gente negativa', reason: 'te hacen sentir como el hoyo cuando estás con ellas', featured: true )
Shit.create(author: 'Las descisiones', reason: 'siempre tenís que dejar cosas atrás y quedai lleno de dudas con qué hubiera pasado', featured: true )
Shit.create(author: 'La gente que habla de ti sin conocerte', reason: 'creen que pueden andar juzgándote y en verdad no saben cómo eres realmente', featured: true )
Shit.create(author: 'Jara', reason: 'es un futbolista, no un jugador de emboque anal', featured: true )
Shit.create(author: 'Jara', reason: 'con las weás que hace caga la imagen de Chile', featured: true )
Shit.create(author: 'Jara', reason: 'nadie puede ser tan desubicado como para meterle el dedo en el poto a su contrincante y aparte después tirarse al suelo ', featured: true )
Shit.create(author: 'La Bachelet', reason: 'es terrible de flaite que vaya a los partidos para que suba su aprobación nomás', featured: true )
Shit.create(author: 'Las inseguridades', reason: 'hacen que las personas actuemos de forma estúpida y nos enojemos con nosotros mismo después', featured: true )
Shit.create(author: 'Jara', reason: 'nada que ver andar provocando y aparte de esa forma tan grosera', featured: true )
Shit.create(author: 'Jara', reason: 'hizo la weá más desubicada que he visto en mucho tiempo', featured: true )
Shit.create(author: 'Las fotos de perfil con la bandera gay', reason: 'se legalizó el matrimonio homosexual en E.E.U.U. no en Chile', featured: true )
Shit.create(author: 'La ansiedad', reason: 'me hace comer y comer y engordar y después odiarme a mi misma', featured: true )
Shit.create(author: 'Dav UC', reason: 'desprecia la diversidad, la comedia y las cosas entretenidas y está lleno de hipsters pretenciosos', featured: true )
Shit.create(author: 'Al weon penca de Vidal', reason: 'es una verguenza como futbolista y ojalá lo castiguen sin jugar por penca', featured: true )
Shit.create(author: 'Alicia', reason: 'siempre llega tarde', featured: true )
Shit.create(author: 'Banner UC', reason: 'me dejó la cagá para la toma de ramos, es demasiado discriminatorio y seguro no va a funcionar bien', featured: true )
Shit.create(author: 'Los trabajos en grupo', reason: 'no te dejan hacer lo que quieres y no te ayudan y para el colmo te critican', featured: true )
Shit.create(author: 'Esos hombres', reason: 'crean rollos en mi imaginacón', featured: true )
Shit.create(author: 'Las calorías', reason: 'nos cagan el ego, la imagen y el futuro', featured: true )
Shit.create(author: 'Allende y Pinochet', reason: 'lo único que hicieron fue dejar un país dividido', featured: true )
Shit.create(author: 'Los profesores', reason: 'ponen criterios de eximición que son un mito', featured: true )
Shit.create(author: 'El trabajo que no he empezado', reason: 'me va a dejar con unas ojeras del terror para mañana', featured: true )
Shit.create(author: 'Las fotos que se saca la gente en la expo de la Kusama', reason: 'se creen súper shoros artistas y en verdad van a posar nomás', featured: true )
Shit.create(author: 'El horóscopo', reason: 'hippies vagos de mierda', featured: true )
Shit.create(author: 'La Universidad', reason: 'este semestre culiao me tiene chata con puras notas mediocres y profesores exigentes', featured: true )
Shit.create(author: 'Las espinillas', reason: 'me cagan todo el autoestima y ganas de hacer cosas', featured: true )
Shit.create(author: 'Hola soy Germán', reason: 'su voz y actitud es irritante', featured: true )
Shit.create(author: 'La puta Vida', reason: 'odio el fin de semestre', featured: true )
Shit.create(author: 'Los lápices de mina verde que se pueden doblar', reason: 'al doblarlos mucho se quiebran', featured: true )
Shit.create(author: ' La Mierda', reason: 'los malditos intestinos me están haciendo cagar cada 10 minutos', featured: true )
Shit.create(author: 'Mi ex', reason: 'me decía que me amaba y no le costó nada dejarme por otro', featured: true )
Shit.create(author: 'El wn que me cantó juegos de seducción en un carrete', reason: 'después nunca más me habló', featured: true )
Shit.create(author: 'El sistema educacional', reason: 'tengo que ocupar tiempo para estudiar en la casa y se supone que ahí debiera descansar y estar con mi familia', featured: true )
Shit.create(author: 'El insulto Raro', reason: 'quién no es raro al final, raro tú', featured: true )